version: '3.8'
services:
  db:
    image: docker.io/mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: '@flyway.user@'
      MONGO_INITDB_ROOT_PASSWORD: '@flyway.password@'
    ports:
      - 27017:27017
  mongo-express:
    image: docker.io/mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: '@flyway.user@'
      ME_CONFIG_MONGODB_ADMINPASSWORD: '@flyway.password@'
      ME_CONFIG_MONGODB_URL: 'mongodb://@flyway.user@:@flyway.password@@mongo:27017/'
networks:
  default:
    driver: bridge